oak:
  ros__parameters:
    camera:
      i_enable_imu: false
      i_enable_ir: false
      i_pipeline_type: RGBD
      #i_publish_tf_from_calibration: true
    stereo:
      i_publish_topic: false
      #i_reverse_stereo_socket_order: true
      #i_publish_synced_rect_pair: true
      i_update_ros_base_time_on_ros_msg: true
  rgb:
    i_height: 1080
    i_width: 1920
    #left:
    #  i_resolution: '400'
    #  i_fps: 90.0
    #right:
    #  i_resolution: '400'
    #  i_fps: 90.0